# Generated by Django 5.2.16 on 2026-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Conversation name"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(max_length=5000, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="message",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Review status",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="rejection_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Rejection reason"
            ),
        ),
    ]
