# Generated by Django 5.2.16 on 2026-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment_content_type",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Attachment content type"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_data",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="Attachment data"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_size",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Attachment size"
            ),
        ),
    ]
