# Generated by Django 5.1.11 on 2026-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_doctorprofile_weekend_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorappointment",
            name="payment_status",
            field=models.CharField(
                choices=[("awaiting", "Chờ thanh toán"), ("paid", "Đã thanh toán")],
                default="awaiting",
                max_length=20,
            ),
        ),
    ]
