# Generated by Django 5.1.11 on 2026-07-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_doctorappointment_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnosis")),
                ("treatment", models.TextField(blank=True, verbose_name="Treatment")),
                (
                    "prescription",
                    models.TextField(blank=True, verbose_name="Prescription"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Doctor's notes")),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Follow-up date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="accounts.doctorappointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment__appointment_date", "-updated_at"],
            },
        ),
    ]
