# Generated by Django 5.1.11 on 2026-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_medicalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="training_history",
            field=models.TextField(blank=True, verbose_name="Training history"),
        ),
    ]
