# Generated by Django 5.1.11 on 2026-07-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_doctorprofile_training_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="years_experience",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Years of experience"
            ),
        ),
    ]
