# Generated by Django 5.1.11 on 2026-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_doctorprofile_years_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="introduction",
            field=models.TextField(blank=True, verbose_name="Introduction"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="position",
            field=models.CharField(blank=True, max_length=150, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialties",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Specialties"
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="workplace",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Workplace"
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Country"),
        ),
    ]
