# Generated by Django 5.1.11 on 2026-07-22 11:43

from django.db import migrations, models


def approve_existing_appointments(apps, schema_editor):
    DoctorAppointment = apps.get_model("accounts", "DoctorAppointment")
    DoctorAppointment.objects.update(moderation_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_appointmentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorappointment",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending admin review"),
                    ("approved", "Approved by admin"),
                    ("rejected", "Rejected by admin"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(approve_existing_appointments, migrations.RunPython.noop),
    ]
