# Generated by Django 5.2.16 on 2026-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_mysql_active_appointment_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorappointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("awaiting", "Awaiting payment"),
                    ("paid", "Paid"),
                    ("expired", "Payment expired"),
                ],
                default="awaiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctorappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending confirmation"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="custom_work_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Custom end time"
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="custom_work_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Custom start time"
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="weekend_off",
            field=models.BooleanField(
                default=False, verbose_name="Closed on Saturdays and Sundays"
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="work_schedule_type",
            field=models.CharField(
                choices=[
                    ("office", "Office hours"),
                    ("night", "Night shift"),
                    ("custom", "Custom"),
                ],
                default="office",
                max_length=20,
            ),
        ),
    ]
