"""
Django settings for mediall_en project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decimal import Decimal
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# 1. Khai báo các domain được phép gửi request CSRF (Bắt buộc phải có https://)
CSRF_TRUSTED_ORIGINS = [
    'https://mediall.net',
    'https://www.mediall.net',
    'https://vi.mediall.net',
    'https://khambenh.azo.vn',
    'https://mediall.azo.vn',
]

# 2. Bật dòng này để Django nhận biết request HTTPS được gửi từ Reverse Proxy (Nginx/Cloudflare)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t@x=42(__0$_vz!1$8w#9_@l!42#0ta^3lft(&nr&@e-(i*^nb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'mediall.net', 'www.mediall.net', 'vi.mediall.net',
    'khambenh.azo.vn', 'mediall.azo.vn',
    '103.188.82.158', 'localhost', '127.0.0.1', '*',
]

RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "")
USD_TO_VND_RATE = Decimal(os.getenv("USD_TO_VND_RATE", "25000"))


# Application definition

INSTALLED_APPS = [
    "accounts",
    "doctors",
    "chat",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mediall_en.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.ui_localization",
            ],
        },
    },
]

WSGI_APPLICATION = "mediall_en.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mediall_en.db.backends.mysql_retry",
        "NAME": os.environ.get("APP_DB_NAME", "mediall_en"),
        "USER": os.environ.get("APP_DB_USER", os.environ.get("DB_USER", "")),
        "PASSWORD": os.environ.get("APP_DB_PASSWORD", os.environ.get("DB_PASSWORD", "")),
        "HOST": os.environ.get("APP_DB_HOST", os.environ.get("DB_HOST", "")),
        "PORT": int(os.environ.get("APP_DB_PORT", os.environ.get("DB_PORT", "3306"))),
        # The database account is limited to 20 connections. Closing each
        # request connection prevents threaded polling from exhausting them.
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "0")),
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": 10,
            "read_timeout": 60,
            "write_timeout": 60,
            "init_command": "SET SESSION sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"  # Đã thêm dấu / ở đầu

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Thêm STATIC_ROOT để gom tất cả file static lại một nơi cho Nginx đọc
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
